Header
mr-svetley/Nerds-Elen pull request #1
Opened 2017-12-20 20:59 UTC by ryazantseva

2017-12-20 21:03 UTC, mr-svetley commented on css/style.css
> +.header{
Хэдер должен тянуться на всю ширину

2017-12-21 10:05 UTC, mr-svetley requested changes

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +    font-family: "Roboto", "Arial", sans-serif;
Вчера как раз обсуждал этот вопрос на slack. Шрифт лучше указывать внутри каждого блока, дабы его можно было легко изменить и дабы сохранить независимость блоков. Если требуется, то шрифт переопределяется для нужных элементов.

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +    height: 545px;
Хэдеру, да и блокам вообще, лучше не задавать высоту, а использовать внутренние элементы, как распорки, у которых мы можем указать высоту (кнопки, элементы меню ...). Если в блоке может случиться переполнение контента, а высоту нужно указать, то лучше использовать min-height

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +    align-items: center;
Навигации задаем центрирование и падинги

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +}
Селекторы по тегам НЕ используем. Тем более глобальные селекторы по тегам, что грешно. (глобальные селекторы по тегам можно использовать только для обговоренных в академии случаях.

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +    position: absolute;
Позиционирование пседоэлемента в данном случае (да и вообще, наверное) лучше делать внутри родительского элемента. т.е. внутри header_bag

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +    margin: 0 auto;
Высоту лучше задавать не слайдеру, а слайду. А слайдеру вообще не указывать высоту или задать минимальную.

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +    margin-bottom: 0;
Селекторы с тегами не используем. Перечисление селекторов следует избегать. (исключение - селекторы с псевдоклассами :hover :focus ...)

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +}
Глобальные классы лучше обособлять префиксом g- . И выносить их в начало (если не предполагается их переопределение) или в конец.

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +    font-weight: 500;
Шрифт лучше вынести в ближайший родительский блок. ( font-family)

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +    margin-bottom: 40px;
Падинг лучше задать самому слайду.

2017-12-21 10:05 UTC, mr-svetley commented on css/style.css
> +    background-color: #fb565a;
Переделать кнопку как отдельный блок с модификатором по цветам. По умолчанию сделайте ее инлайн-блоком.

2017-12-21 10:07 UTC, mr-svetley approved these changes

2017-12-21 10:10 UTC, ryazantseva commented on css/style.css
> +}
что грешно (с) ну мы же не святые)

2017-12-21 10:13 UTC, mr-svetley requested changes

2017-12-21 10:13 UTC, mr-svetley commented on index.html
> +            <svg xmlns="http://www.w3.org/2000/svg" width="160" height="65" viewBox="0 0 160 65"><path d="M157.936 49.374c-1.235.161-2.523.271-3.757.377v.056c-2.415 17.364-26.188 20.231-26.779 6.599-
logo - ссылка

2017-12-21 10:13 UTC, mr-svetley commented on index.html
> +                    <li class="header-menu_item">СТУДИЯ</li>
Не нужная обертка header_menu

2017-12-21 10:13 UTC, mr-svetley commented on index.html
> +                </ul>
Пункты меню - ссылки

2017-12-21 10:13 UTC, mr-svetley commented on index.html
> +           </div>
Это мы договорились сделать списком. Корзина - ссылка.

2017-12-21 10:13 UTC, mr-svetley commented on index.html
> +                  <button value="УЗНАТЬ БОЛЬШЕ"></button>
Добавить классы. "Узнать больше" - ссылка

2017-12-24 16:15 UTC, ryazantseva commented on index.html
> +            <svg xmlns="http://www.w3.org/2000/svg" width="160" height="65" viewBox="0 0 160 65"><path d="M157.936 49.374c-1.235.161-2.523.271-3.757.377v.056c-2.415 17.364-26.188 20.231-26.779 6.599-
done

2017-12-24 16:15 UTC, ryazantseva commented on index.html
> +                    <li class="header-menu_item">СТУДИЯ</li>
done

2017-12-24 16:15 UTC, ryazantseva commented on index.html
> +                </ul>
done

2017-12-24 16:15 UTC, ryazantseva commented on index.html
> +           </div>
done

2017-12-24 16:15 UTC, ryazantseva commented on index.html
> +                  <button value="УЗНАТЬ БОЛЬШЕ"></button>
done

2017-12-26 17:56 UTC, ryazantseva commented on css/style.css
> +.header{
поставила 100%

2017-12-26 18:00 UTC, ryazantseva commented on css/style.css
> +    height: 545px;
done
убила высоту

2017-12-26 18:13 UTC, ryazantseva commented on css/style.css
> +    font-family: "Roboto", "Arial", sans-serif;
убрала из body прописала в блоках

2017-12-26 18:20 UTC, ryazantseva commented on css/style.css
> +}
убито

2017-12-26 18:29 UTC, ryazantseva commented on css/style.css
> +    position: absolute;
done

2017-12-26 18:33 UTC, ryazantseva commented on css/style.css
> +    margin: 0 auto;
done

2017-12-26 18:41 UTC, ryazantseva commented on css/style.css
> +    margin-bottom: 0;
done

2017-12-26 18:51 UTC, ryazantseva commented on css/style.css
> +.header{
ок auto

2017-12-26 18:53 UTC, mr-svetley commented on css/style.css
> +    font-weight: 500;
И другие параметры шрифта общие для для всех элементов блока, тоже лучше вынести.

2017-12-26 19:01 UTC, ryazantseva commented on css/style.css
> +    margin-bottom: 40px;
м, ну мы подумаем, куда его пристроить, пока просто уберу здесь

2017-12-26 19:02 UTC, ryazantseva commented on css/style.css
> +    font-weight: 500;
done

2017-12-26 19:15 UTC, ryazantseva commented on css/style.css
> +}
done
вот теперь хаос стал окончательным)

2017-12-26 19:15 UTC, mr-svetley commented on css/style.css
> +    align-items: center;
Центрирование и падиги самого блока header_nav. (margin: 0 auto).

2017-12-26 19:30 UTC, mr-svetley commented on css/style.css
> +}
Все норм, просто в html тоже имя класса нужно поправить

2017-12-31 18:24 UTC, mr-svetley requested changes

2017-12-31 18:24 UTC, mr-svetley commented on index.html
> +            </ul>
Стоит назвать класс списка header_user-menu и от него внутренности поменять. Ведь мы же договаривались, что в перспективе, в этом списке возможны элементы типа "войти", "выйти", "мой профиль". А с учетом текущих имен классов -  эти элементы будет странно добавлять в список с классом header_bag. Или переделайте, как изначально было - просто ссылка.

2017-12-31 18:24 UTC, mr-svetley commented on index.html
> +                  <a class="button slider_slide-button" href="#">УЗНАТЬ БОЛЬШЕ</a>
Просто на заметку, править не нужно - slider_slide-button можно сократить до slider_button

2017-12-31 18:25 UTC, mr-svetley approved these changes

2017-12-31 18:51 UTC, mr-svetley requested changes

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +
В чем отличие глобальных стилей и глобальных классов? Глобальные стили (они же стили по тегам, без экранирования их классами) мы не используем. Глобальные классы - классы, которые могут дополнительно прописываться в любом блоке или элементе. Такой класс у вас один - g-visually-hidden. Поправьте названия разделов css-файла.

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +
У хэдера по умолчанию ширина auto. Данная запись излишняя, но можете оставить.

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +    padding: 0;
Вот пример разрешенного использования глобальных стилей - обнуление боди. Вот над этим правилом можно было-бы написать global styles

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +    align-items: center;
Падинги! Без них содержимое прилипает к краям браузера на низких разрешениях. (ширина 1200 + падинги по бокам по 20пикселей)

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +}
Проще было задать отступ для всего header_nav, а элементы внутри просто отцентрировать по вертикале.

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +}
проще было через opacity, как в макете сделано.

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +    position: absolute;
В первый раз не обратил внимание. Иконку лучше делать псевдоэлементом от ссылки. Ибо текст и иконка образуют одну цельную ссылку.

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +    list-style-type: none;
Обнуление стилей списка лучше делать на классе самого списка, а не на его элементе. Хотя можно и так оставить.

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +    margin: 0 auto;
То же, что и с header_nav - ширина и падинги

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +    height: 420px;
Не понятно зачем проценты, тем более в такой величине. И мы договаривались помнить о переполнении контентом (фиксированная высота - не комильфо в данном случае)

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +    font-size: 16px;
Стили базового шрифта выносим в родительский блок - slider

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +    line-height: 18px;
Шрифт у всех кнопок одинаковый, следовательно его нужно вынести в блок кнопки - .btn

2017-12-31 18:51 UTC, mr-svetley commented on css/style.css
> +    position: absolute;
Абсолютное позиционирование здесь излишне. Конторолы вполне можно сделать и поточными. А вот блок контролов, да, нужно позиционировать.

2017-12-31 18:56 UTC, mr-svetley commented on css/style.css
> +    height: 420px;
Понял к чему это. И это не правильно. У тебя еще картинка не к конкретному слайде относиться, а ко всему слайдеру. А картинка на каждом слайде своя.

2017-12-31 18:57 UTC, mr-svetley commented on css/style.css
> +    position: absolute;
контролы недоступны для нажатия, ибо они под каким-то слоем.

2018-01-02 19:41 UTC, mr-svetley approved these changes

2018-01-02 19:41 UTC, merged