Services
mr-svetley/Nerds-Elen pull request #2
Opened 2018-01-03 15:31 UTC by ryazantseva

2018-01-03 18:08 UTC, mr-svetley requested changes

2018-01-03 18:08 UTC, mr-svetley commented on index.html
> +              <img class="service-1" src="img/service-1.png" width="300" height="146">
А где ul ? Использовать li вне UL or OL нельзя.

2018-01-03 18:08 UTC, mr-svetley commented on index.html
> +              <p class="services-text">Покорите топ-10 приложений в AppStore и Google Play</p>
С нумерацией заголовков нужно поработать. У заголовка слайдера и этого заголовка должен быть один уровень. Попробуйте на бумаге написать древовидную структуру документа (по заголовкам) и восстановить логические заголовки (которых нет в дизайне, но которые должны быть по логике)

2018-01-03 18:08 UTC, mr-svetley commented on index.html
> +              <h4 class="services-title">Презентации</h4>
Картинка здесь скорее декоративная, но вопрос через что (css или html) прописывать картинки лучше - риторический. Поэтому можно оставить так.

2018-01-03 18:08 UTC, ryazantseva commented on index.html
> +              <img class="service-1" src="img/service-1.png" width="300" height="146">
аааа!

2018-01-03 18:12 UTC, mr-svetley commented on index.html
> +              <img class="service-1" src="img/service-1.png" width="300" height="146">
Через валидатор можно было проверить. Он бы заругался)

2018-01-03 18:18 UTC, ryazantseva commented on index.html
> +              <p class="services-text">Покорите топ-10 приложений в AppStore и Google Play</p>
согласна, это h3

2018-01-13 17:14 UTC, mr-svetley requested changes

2018-01-13 17:14 UTC, mr-svetley commented on index.html
> +              <ul class="about-us_info-list">
имя класса

2018-01-13 17:14 UTC, mr-svetley commented on index.html
> +              <ul class="about-us_stat-list">
так же дефис в имени класса. И неверно задано имя для лого. Где блок stat, от которого задано имя?

2018-01-13 17:14 UTC, mr-svetley commented on index.html
> +              <p class="services-text">Мир никогда не будет прежним<br> после того как увидит ваш сайт!</p>
Это не блоки, а элементы. (дефисы)

2018-01-13 17:15 UTC, ryazantseva commented on index.html
> +              <ul class="about-us_info-list">
м?

2018-01-13 17:17 UTC, mr-svetley commented on index.html
>                    <p class="slider_slide-text">Математически выверенный дизайн<br> для вашего сайта или мобильного приложения.</p>
А где выше h1 и h2? Нужно их пописать чтобы здесь h3 можно было поставить.

2018-01-13 17:19 UTC, ryazantseva commented on index.html
> +              <p class="services-text">Мир никогда не будет прежним<br> после того как увидит ваш сайт!</p>
services_cards заменила на services-cards

2018-01-13 17:36 UTC, mr-svetley commented on index.html
> +              <p class="services-text">Мир никогда не будет прежним<br> после того как увидит ваш сайт!</p>
Нет, верните назад. Другие классы.  service-1, services-title ...

2018-01-13 17:36 UTC, mr-svetley commented on index.html
> +              <ul class="about-us_info-list">
"about-us_info-titlelist" дефис и буква

2018-01-13 17:45 UTC, ryazantseva commented on index.html
> +              <p class="services-text">Мир никогда не будет прежним<br> после того как увидит ваш сайт!</p>
так. я отделяю блоки нижним подчеркиваем _ , а элементы дефисом - . service-1, services-title и services-text элементы services_cards, поэтому я их отделяю -.
Или сделать services_cards-service1, services_cards-title и т.п.?

2018-01-13 17:47 UTC, ryazantseva commented on index.html
> +              <ul class="about-us_info-list">
title-list? про букву упорно не могу понять)

2018-01-13 17:49 UTC, ryazantseva commented on index.html
> +              <ul class="about-us_stat-list">
ааа, кажется поняла что значит дефис в имени класса) about-us вот это?
сделать без дефиса aboutUs?

2018-01-13 17:50 UTC, ryazantseva commented on index.html
> +              <ul class="about-us_info-list">
здесь видимо то же несчастное about-us, но буква осталась непонятной

2018-01-14 15:33 UTC, mr-svetley commented on index.html
> +              <p class="services-text">Мир никогда не будет прежним<br> после того как увидит ваш сайт!</p>
Блок - сам по себе. Элементы от блока отделяешь ты _. Модификаторы блоков и элементов --. Одним дефисом отделяются слова в названии блока, элемента или модификатора. 
Во-первых не services_cards , а services_card (без s, т. к. это ведь одна карточка)
Во-вторых карточка - это повторяющийся блок, значит помимо имеющегося класса "от родителя" следовало задать класс блока (например servise-card)
В-третьих, элементы внутри следует именовать уже от этого блока. (block-name_element-name--modificator-name).

2018-01-14 15:39 UTC, mr-svetley commented on index.html
> +              <ul class="about-us_info-list">
title-list - все верно. На счет буквы - ночное мерещенье)

2018-01-14 15:41 UTC, mr-svetley commented on index.html
> +              <ul class="about-us_stat-list">
Уже поправили выше - titlelist. Нет camelCase - не используем, ибо изначально он не использовался. помним про единообразие кода.

2018-01-14 15:43 UTC, mr-svetley commented on index.html
>                    <p class="slider_slide-text">Математически выверенный дизайн<br> для вашего сайта или мобильного приложения.</p>
Посмотрите мой код и его валидацию с построение outline ( https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fmr-svetley.github.io%2FNerds-Vlad%2F )

2018-01-15 17:37 UTC, mr-svetley requested changes

2018-01-15 17:37 UTC, mr-svetley commented on index.html
> +              <h3 class="service-card_title">Веб-сайты</h3>
Здесь лучше было задать класс service-card_image куда все стили для изображения скинуть. И можификатор этого класса service-card_image--1 куда прописать только backgroun-image.

2018-01-15 17:37 UTC, mr-svetley commented on index.html
> +              <img class="stat_logo-image stat_logo--confetti" src="img/logo-color.png" width="360" height="208" alt="Веб-студия Нёрдс">
именуете от блока stat, а блока stat в в родителях нет

2018-01-15 17:37 UTC, mr-svetley commented on index.html
>                <h3 class="about-us_info-title">Мы – маленькая, но гордая дизайн-студия из Краснодара.</h3>
Это не заголовок. Здесь можно добавить скрытый заголовок  типа "информация о нас", а нижнему блоку "мы в цифрах"

2018-01-15 20:28 UTC, mr-svetley commented on index.html
> +              <img class="about-us_stat-logo about-us_stat_logo--confetti" src="img/logo-color.png" width="360" height="208" alt="Веб-студия Нёрдс">
Здесь модификатор не нужен, ибо других лого в этом блоке не предпологается.

2018-01-15 20:30 UTC, ryazantseva commented on index.html
> +              <img class="about-us_stat-logo about-us_stat_logo--confetti" src="img/logo-color.png" width="360" height="208" alt="Веб-студия Нёрдс">
ну ок, уберу

2018-01-15 20:35 UTC, mr-svetley approved these changes

2018-01-16 20:16 UTC, mr-svetley requested changes

2018-01-16 20:16 UTC, mr-svetley commented on index.html
>                <h3 class="service-card_title">Приложения</h3>
Если контентные картинки стоят, то модификаторы не нужны.

2018-01-16 21:16 UTC, mr-svetley requested changes

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +}
Не обнулен список (padding-lefr и margin) из-за этого блок services шире 1200px. А по тз он должен быть 1200. Из-за этого горизонтальный скрол появится раньше ожидаемого.

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +    margin: 0 auto;
Ширина и падиги такие же, как у nav

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +
list-style обнуляем через список (ol) , а не через элемент (li)

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +    padding-top: 80px;
падинг сверху лучше задать родителю. (листу или секции)

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +    padding-top: 21px;
Не забываем прописывать шрифт изначально в блоке от которого назван элемент.

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +    font-weight: regular;
не regular, а normal

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +    margin-top: 16px;
отступы лучше формировать сверху в низ (верхний элемент отталкивает нижний)

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +    margin: 0 auto;
Ширина и падинги как у nav (помним о единообразии кода)

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +    margin-left: 42px;
падинг сверху лучше задать родителю (верхний элемент толкает нижний)
а марджин будет не нужен когда предыдущий коммент поправите

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +    padding-top: 120px;
Семейство шрифтов стоит задавать КАЖДОМУ блоку для сохранения его независимсоти

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +
Зачем извращяться с отрицательным марджином. когда можно просто поменять падинг слева у самого списка?

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +   font-family: "Roboto", "Arial", sans-serif;
Семейство шрфтов через блок about-us задаем

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +    line-height: 10px;
нельзя задавать высоту строки меньше чем размер шрифта.

2018-01-16 21:16 UTC, mr-svetley commented on css/style.css
> +    font-size: 25px;
Не очень способ, ибо не универсален. Можно было бы каждому about-us_stat-percent задать дисплей инлайн-блок и падинг права на ширину значка процента и абсолютно спозиционировать этот значек.

2018-01-19 22:05 UTC, ryazantseva commented on css/style.css
> +}
обнулено, services теперь 1200

2018-01-19 22:05 UTC, ryazantseva commented on css/style.css
> +    margin: 0 auto;
левый и правый паддинг 20 px

2018-01-19 22:05 UTC, ryazantseva commented on css/style.css
> +    padding-top: 80px;
ага, сделала паддинг у секции

2018-01-19 22:05 UTC, ryazantseva commented on css/style.css
> +
обнулено через ol)

2018-01-19 22:05 UTC, ryazantseva commented on css/style.css
> +    padding-top: 21px;
ага, прописала в services

2018-01-19 22:06 UTC, ryazantseva commented on css/style.css
> +    font-weight: regular;
done

2018-01-19 22:06 UTC, ryazantseva commented on css/style.css
> +    margin-top: 16px;
done

2018-01-22 19:18 UTC, ryazantseva commented on css/style.css
> +    font-size: 25px;
вот тут у меня как-то не пошло. проблема с абсолютным позиционированием значка в том, что у последнего все равно должны быть другие координаты относительно цифр процента, так как там на одну цифру меньше и значок должен поэтому стоять ближе.
инлайн-блок about-us_stat-percent я задала, но на паддинг справа реакции нет вообще никакой)
в общем чего-то я недопоняла)

2018-01-22 19:19 UTC, ryazantseva commented on css/style.css
> +    line-height: 10px;
сделана высоту строки 45 px

2018-01-22 19:19 UTC, ryazantseva commented on css/style.css
> +   font-family: "Roboto", "Arial", sans-serif;
задано

2018-01-22 19:19 UTC, ryazantseva commented on css/style.css
> +
отставить извращения)

2018-01-22 19:19 UTC, ryazantseva commented on css/style.css
> +    margin-left: 42px;
сделано
тут такой момент: паддинг сверху оттолкнул не только блок about-us_info, но и about-us_stat. а там логотип, который стоит не на уровне about-us_info, а выше. поэтому пришлось логотипу задавать отрицательный марджин сверху.

2018-01-22 19:19 UTC, ryazantseva commented on css/style.css
> +    padding-top: 120px;
м, не совсем уверена, задала шрифты для about-us как родительскому блоку

2018-01-22 19:19 UTC, ryazantseva commented on css/style.css
> +    margin: 0 auto;
done

2018-01-22 19:41 UTC, mr-svetley commented on css/style.css
> +    padding-top: 120px;
Там вот как - общие наследуемы стили (например шрифт) мы задаем блоку, дабы не прописывать их в каждом элементе. Можем задать родителю базовый шрифт вместе с размерами и жирностью, а для конкретных элементов переопределять их.

2018-01-22 19:43 UTC, mr-svetley commented on css/style.css
> +    margin-left: 42px;
Тогда лучше тот паддинг задать такой чтоб лого норм встало. а для другого блока задать свой отступ.

2018-01-24 16:16 UTC, mr-svetley commented on index.html
>           <h2 class="g-visually-hidden">Наши преимущества</h2>
Нет. заместо мэин-бэкграунд напиши slider, а вместо slider - slider__wrapper. Так будет логичнее и единообразнее.
и wrapper задаем ширину 1200 и падинги (все как у остальных блоков)

2018-01-27 13:17 UTC, merged